"""create tables


Revision ID: 361d9620baa9
Revises: 8a4b41b88b3b
Create Date: 2023-04-17 18:27:17.243433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361d9620baa9'
down_revision = '8a4b41b88b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=4), nullable=True))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=4), nullable=True))

    # ### end Alembic commands ###
