"""empty message

Revision ID: 7388d5a001c1
Revises: 997335e94400
Create Date: 2023-09-11 16:11:59.770075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7388d5a001c1'
down_revision = '997335e94400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_photos_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_photos_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_photos_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_photos_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
