"""empty message

Revision ID: c65515e8676b
Revises: ff99882d5c02
Create Date: 2023-09-11 17:02:44.359316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65515e8676b'
down_revision = 'ff99882d5c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_photo_id_photos', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_photo_id_photos'), 'photos', ['photo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_likes_photo_id_photos', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_likes_photo_id_photos'), 'photos', ['photo_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_likes_photo_id_photos'), type_='foreignkey')
        batch_op.create_foreign_key('fk_likes_photo_id_photos', 'photos', ['photo_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_photo_id_photos'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_photo_id_photos', 'photos', ['photo_id'], ['id'])

    # ### end Alembic commands ###
