"""Remove unnecessary fields

Revision ID: f83b6e25bbfd
Revises: c65515e8676b
Create Date: 2023-09-22 21:32:58.987311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83b6e25bbfd'
down_revision = 'c65515e8676b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
