"""empty message

Revision ID: ff99882d5c02
Revises: b7ef39c6a229
Create Date: 2023-09-11 16:13:37.728985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff99882d5c02'
down_revision = 'b7ef39c6a229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_likes_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_likes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_likes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_likes_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
